### PR TITLE
Added _no_document_patterns settings for route.

### PR DESCRIPTION
**Pull request by tautelis**
Say we have the following urls in our system:
```
\product\some-product-url
\product\some-product-url-2
\product\some-product-url-3
```
There is a case that for some reason document with `\product\some-product-url-3` url is no longer in database but we want certain logic if user tries to access the this url. Hence, with this PR it is possible to provide a pattern for the controller action fallback when no document was found.
```yml
ongr_router:
     es_manager: default
     seo_routes:
         product:
             _route: ongr_test_document_page
             _controller: AcmeTestBundle:Test:testDocument
             _default_route: ongr_test_show
             _id_param: documentId
             _no_document_patterns: ["^/product/.+$", "^/article/.+$"]
```

### CODE REVIEW

**Comment by martiis** [comment]
@saimaz looks good.

**Comment by tautrimas** [comment]
We should not put that much logic into our single router. Can this situation be handled by adding another route that calls original route by passing `null` `null`?

**Comment by tautelis** [comment]
@tautrimas i thought exactly the same, but.. if you take a look at how matching is handled
https://github.com/ongr-io/RouterBundle/blob/d344d6c28b82fb09183e3e13c2005b6220d9e5a0/Routing/SeoUrlMatcher.php#L101
you will see that it is first attempting to route sf default routes and after it does not find anything it fallbacks to ONGR router. If we add a default route like this the ONGR document will never be loaded.

With this PR the routing hierarchy becomes as follows:
- default SF routes
- ONGR document URLs
- _no_document_pattern routes

**Comment by tautrimas** [comment]
Well, this PR looks damn convenient, I must agree. But it seems that you are trying to mix up not found logic inside the same controller action. My suggestion would be to use custom error controller and handle such and other custom cases. http://symfony.com/doc/current/cookbook/controller/error_pages.html. Maybe there are other solutions? What do people do when Doctrine does not find an entity with id `123`?

**Comment by tautelis** [comment]
Well, your suggestion to handle this stuff by error controller is also pretty solid, I must agree :)

**Pull request closed without merging**
