### PR TITLE
SeoMatcher tests refactored

### PR DESCRIPTION
**Pull request by asev**
SeoMatcher tests didn't test much, was complex with code duplication and not all cases had comments.

This pull request fails because of #51.

### CODE REVIEW

**Comment by asev** [comment]
Failing tests fixed. Closes #51

**Comment by murnieza** [comment]
LGTM. @saimaz @mvar ?

**Comment by saimaz** [comment]
IMO would make sense if could remove trailing slash requirement in this PR also. What do you think @asev ?

**Comment by asev** [comment]
I was planning to not mix them up, but ok. I'll merge it here.

**Comment by saimaz** [comment]
Dont foget to add this change to the upcomming docs.

**Pull request merged**
